### ISSUE TITLE
Compare quality of all classification models

### ISSUE THREAD

**Issue by 7ben18** [Immobilienrechner-Challenge/classification-objecttype#1]

**Comment by gabrieltorresgamez** [comment]
Überprüfen was wir haben und ob wir noch etwas verbessern können/ oder neues Modell implementieren (z.B. Random Forest)

**Comment by gabrieltorresgamez** [comment]
Bericht zu unseren Modellen

**Comment by gabrieltorresgamez** [comment]
Wieso wurde dieses Ticket auf cancelled gestellt?
