### ISSUE TITLE
Create Multi-Layer-Perceptron

### ISSUE THREAD

**Issue by hariveliki** [Immobilienrechner-Challenge/classification-objecttype#4]

**Comment by gabrieltorresgamez** [comment]
PyTorch Modell erstellt. Muss noch Early Stopping implementieren.

**Comment by gabrieltorresgamez** [comment]
https://github.com/Bjarten/early-stopping-pytorch/blob/master/MNIST_Early_Stopping_example.ipynb

**Comment by gabrieltorresgamez** [comment]
done

**Comment by gabrieltorresgamez** [comment]
Dokumentation nachführen.
