### ISSUE TITLE
Create k-Nearest-Neighbour model

### ISSUE THREAD

**Issue by hariveliki** [Immobilienrechner-Challenge/classification-objecttype#5]

**Comment by gabrieltorresgamez** [comment]
@gabrieltorresgamez anschauen

**Comment by gabrieltorresgamez** [comment]
done

https://github.com/Immobilienrechner-Challenge/classification-objecttype/blob/main/test_K_Neighbors_Classifier.ipynb

**Comment by gabrieltorresgamez** [comment]
Dokumentation nachführen
